# Autogenerated wrapper script for VkFFT_OpenCL_jll for riscv64-linux-gnu
export libvkfft

using OpenCL_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("VkFFT_OpenCL")
JLLWrappers.@declare_library_product(libvkfft, "libvkfft.so")
function __init__()
    JLLWrappers.@generate_init_header(OpenCL_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libvkfft,
        "lib/libvkfft.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
